adding queue implementation[@Noran,@ABadr]
AbdelrahmanBadr22/C_DataStructure_G1 pull request #33
Opened 2022-11-07 16:56 UTC by noran97

2022-11-08 20:29 UTC, AbdelrahmanBadr22 requested changes

2022-11-08 20:29 UTC, AbdelrahmanBadr22 commented on conf.h
> +#define arraysize    (100)
always make macros name uppercase separated by `_` character e.g. `ARRAY_SIZE`

2022-11-08 20:29 UTC, AbdelrahmanBadr22 commented on conf.h
> +#endif
its preferred to write a comment beside `#endif` to make `#if` clear e.g. `#endif //QUEUE_TYPE`

2022-11-08 20:29 UTC, AbdelrahmanBadr22 commented on conf.h
> +#ifndef CONF_H_INCLUDED
rename this file `Queue_Cong.h`

2022-11-08 20:29 UTC, AbdelrahmanBadr22 commented on queu.h
> +#ifndef QUEU_H_INCLUDED
rename this file `Queue.h` to be compatible with other files

2022-11-08 20:54 UTC, AbdelrahmanBadr22 requested changes

2022-11-08 20:54 UTC, AbdelrahmanBadr22 commented on Queue_Cong.h
> +#define QUEUE_ARRAY   (2)
`Queue_Cong` !! 
make it `Queue_Config`

2022-11-08 20:54 UTC, AbdelrahmanBadr22 commented on queue.c
> +typedef struct queue {
make this file named `Queue.c` ya noraaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaan

2022-11-08 20:54 UTC, AbdelrahmanBadr22 commented on queue.c
> +#include "conf.h"
اقسم بالله المفروض نعمل build ونتأكد انه بيعمل build قبل نعمل push عشان منبوظش اكواد الناس التانيه

2022-11-09 18:20 UTC, noran97 commented on queue.c
> +typedef struct queue {
شاهد شخص يحكم على الكتاب من عنوانه 
حاضر هغيره يا بشمهندس 👩‍🦯👩‍🦯

2022-11-10 18:17 UTC, AbdelrahmanBadr22 commented on Queue.h
> +uint16_t queue_GetSize(queue_t*q);
Prototypes of function for both implementations are same so no need to guard with `#if` or #else` and make the first character uppercase as follows `Queue_Initiate()` `Queue_Push` ...

2022-11-10 18:18 UTC, AbdelrahmanBadr22 commented on Queue.h
> + #else
`#elif ...` will be better as in case of error no functions exists

2022-11-10 18:19 UTC, AbdelrahmanBadr22 commented on Queue_Config.h
> +#define Array_Size    (100)
it's preferred to make all macros in uppercase e.g. `#define ARRAY_SIZE`

2022-11-10 18:20 UTC, AbdelrahmanBadr22 commented on Queue_Config.h
> +#error "Error in defining QUEUE_TYPE "
it's preferred in error message to refer to file name e.g. `"ERROR IN DEFINING QUEUE_TYPE @Queue_Config.h`

2022-11-10 20:27 UTC, AbdelrahmanBadr22 commented on Queue.h
> +uint16_t arr[ARRAY_SIZE];
make the type of array as a macro and make the user determine which type he want e.g. `typedef   QueueType uint16`

2022-11-10 20:28 UTC, AbdelrahmanBadr22 commented on Queue.h
> +uint16_t i;
`i` really ? 
what is the meaning of that ???

2022-11-10 20:28 UTC, AbdelrahmanBadr22 commented on Queue.h
> +}queue_t;
make it compatible with other code e.g. `Queue_t`

2022-11-11 17:23 UTC, merged